services:
  mysql:
    image: mysql:8.0
    container_name: mysql_sismos
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sismos
      MYSQL_PASSWORD: root
    volumes:
      - ./Base de datos/scripts:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"
    networks:
      - sismos_network

  app:
    build:
      context: ./Desarrollo/Back/sismos
    container_name: practica1-container-levantado
    environment:
      mp.openapi.extensions.smallrye.info.title: Sismos
      mp.openapi.extensions.smallrye.info.description: API Rest que implementa los endpoints del sistema sismos
      quarkus.swagger-ui.display-operation-id: true
      quarkus.swagger-ui.theme: original
      quarkus.swagger-ui.always-include: true
      quarkus.datasource.db-kind: mysql
      quarkus.datasource.username: root
      quarkus.datasource.password: root
      quarkus.datasource.jdbc.url: jdbc:mysql://mysql_sismos:3306/sismos
      quarkus.http.access-log.enabled: true
      quarkus.hibernate-orm.packages: mx.com.escom.sismos.external.jpa.model
    ports:
      - "9090:8080"
    depends_on:
      - mysql
    networks:
      - sismos_network
    volumes:
      - ./src/main/resources:/deployments/config

  frontend:
    build:
      context: ./Desarrollo/Front
    container_name: frontend_sismos
    ports:
      - "3000:80"
    depends_on:
      - app
    networks:
      - sismos_network

networks:
  sismos_network:
    driver: bridge
