-- MySQL Script generated by MySQL Workbench
-- Wed Apr 23 00:17:04 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema sismos
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `sismos` ;

-- -----------------------------------------------------
-- Schema sismos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sismos` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `sismos` ;

-- -----------------------------------------------------
-- Table `sismos`.`placas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sismos`.`placas` (
  `placa_id` INT NOT NULL AUTO_INCREMENT,
  `nombre` TEXT NOT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  `geom` MULTIPOLYGON NOT NULL,
  PRIMARY KEY (`placa_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sismos`.`registros_sismos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sismos`.`registros_sismos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `magnitud` DECIMAL(3,1) NOT NULL,
  `latitud` DECIMAL(7,4) NOT NULL,
  `longitud` DECIMAL(7,4) NOT NULL,
  `profundidad` DECIMAL(5,1) NOT NULL,
  `referencia_localizacion` TEXT NULL DEFAULT NULL,
  `fecha_utc` DATE NOT NULL,
  `hora_utc` TIME NOT NULL,
  `estatus` VARCHAR(20) NULL DEFAULT NULL,
  `placa_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_registros_sismos_placas`
    FOREIGN KEY (`placa_id`)
    REFERENCES `sismos`.`placas` (`placa_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9563
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_registros_sismos_placas_idx` ON `sismos`.`registros_sismos` (`placa_id` ASC) VISIBLE;

DELIMITER //

CREATE TRIGGER asignar_placa_antes_insert
BEFORE INSERT ON registros_sismos
FOR EACH ROW
BEGIN
  DECLARE id_placa INT;

  SELECT placa_id INTO id_placa
  FROM placas
  ORDER BY ST_Distance(
    geom,
    ST_GeomFromText(CONCAT('POINT(', NEW.longitud, ' ', NEW.latitud, ')'))
  )
  LIMIT 1;

  SET NEW.placa_id = id_placa;
END //

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
