-- MySQL Script generated by MySQL Workbench
-- Wed Apr 23 00:17:04 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema sismos
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `sismos` ;

-- -----------------------------------------------------
-- Schema sismos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sismos` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `sismos` ;

-- -----------------------------------------------------
-- Table `sismos`.`placas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sismos`.`placas` (
  `placa_id` INT NOT NULL AUTO_INCREMENT,
  `nombre` TEXT NOT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  `geom` MULTIPOLYGON NOT NULL,
  PRIMARY KEY (`placa_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sismos`.`registros_sismos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sismos`.`registros_sismos` (
  `id_registros_sismos` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `magnitud` DECIMAL(3,1) NOT NULL,
  `latitud` DECIMAL(7,4) NOT NULL,
  `longitud` DECIMAL(7,4) NOT NULL,
  `profundidad` DECIMAL(5,1) NOT NULL,
  `referencia_localizacion` TEXT NULL DEFAULT NULL,
  `fecha_utc` DATE NOT NULL,
  `hora_utc` TIME NOT NULL,
  `estatus` VARCHAR(20) NULL DEFAULT NULL,
  `placa_id` INT NOT NULL,
  PRIMARY KEY (`id_registros_sismos`),
  CONSTRAINT `fk_registros_sismos_placas`
    FOREIGN KEY (`placa_id`)
    REFERENCES `sismos`.`placas` (`placa_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9563
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_registros_sismos_placas_idx` ON `sismos`.`registros_sismos` (`placa_id` ASC) VISIBLE;

DELIMITER //

CREATE TRIGGER asignar_placa_antes_insert
BEFORE INSERT ON registros_sismos
FOR EACH ROW
BEGIN
  DECLARE id_placa INT;

  SELECT placa_id INTO id_placa
  FROM placas
  ORDER BY ST_Distance(
    geom,
    ST_GeomFromText(CONCAT('POINT(', NEW.longitud, ' ', NEW.latitud, ')'))
  )
  LIMIT 1;

  SET NEW.placa_id = id_placa;
END //

DELIMITER ;

CREATE TABLE IF NOT EXISTS `sismos`.`sensores` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `codigo` varchar(10) NOT NULL,
  `nombre` varchar(35) NOT NULL,
  `estado` varchar(45) NOT NULL,
  `latitud` DECIMAL(7,4) NOT NULL,
  `longitud` DECIMAL(7,4) NOT NULL,
  `red` varchar(10) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
-- Crear la tabla
CREATE TABLE volcanes (
    id_volcan INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(100),
    latitud DECIMAL(10, 4),
    longitud DECIMAL(11, 4)
);

  CREATE TABLE volcanes_afectados (
    id_volcan INT NOT NULL,
    id_registros_sismos INT NOT NULL,
    PRIMARY KEY (id_volcan, id),
    FOREIGN KEY (id_volcan) REFERENCES volcanes(id_volcan),
    FOREIGN KEY (id_registros_sismos) REFERENCES registros_sismos(id_registros_sismos)
  );

ALTER TABLE volcanes_afectados
ADD COLUMN distancia_km DECIMAL(7,2) AFTER id_registros_sismos;


DELIMITER $$

CREATE TRIGGER volcanes_afectados_trigger
AFTER INSERT ON registros_sismos
FOR EACH ROW
BEGIN
DECLARE done INT DEFAULT FALSE;
DECLARE v_id INT;
DECLARE v_lat DECIMAL(10, 4);
DECLARE v_lon DECIMAL(11, 4);
DECLARE distancia DOUBLE;
DECLARE radio DOUBLE;

-- Cursor para recorrer todos los volcanes
DECLARE volcanes_cursor CURSOR FOR
SELECT id_volcan, latitud, longitud FROM volcanes;

DECLARE CONTINUE HANDLER FOR NOT FOUND SET done = TRUE;

-- Determinar radio de afectación según magnitud del sismo
IF NEW.magnitud <= 4.0 THEN
SET radio = 30;
ELSEIF NEW.magnitud <= 6.0 THEN
SET radio = 70;
ELSEIF NEW.magnitud <= 7.0 THEN
SET radio = 120;
ELSE
SET radio = 200;
END IF;

-- Abrimos el cursor
OPEN volcanes_cursor;

volcan_loop: LOOP
FETCH volcanes_cursor INTO v_id, v_lat, v_lon;
IF done THEN
LEAVE volcan_loop;
END IF;
-- Calcular distancia usando la fórmula de Haversine
SET distancia = 6371 * ACOS(
  COS(RADIANS(NEW.latitud)) *
  COS(RADIANS(v_lat)) *
  COS(RADIANS(v_lon) - RADIANS(NEW.longitud)) +
  SIN(RADIANS(NEW.latitud)) *
  SIN(RADIANS(v_lat))
);

-- Si está dentro del radio, insertamos en la tabla intermedia
IF distancia <= radio THEN
  INSERT IGNORE INTO volcanes_afectados (id_volcan, id_registros_sismos, distancia_km)
  VALUES (v_id, NEW.id_registros_sismos, ROUND(distancia, 2));
END IF;
END LOOP;

-- Cerramos el cursor
CLOSE volcanes_cursor;
END $$

DELIMITER ;


DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
