name: Notificar a Discord estilo Webhook

on:
  push:

jobs:
  discordNotification:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar notificación a Discord
        run: |
          COMMIT_LIST=""
          for COMMIT in $(jq -r '.commits[].id' <<< '${{ toJson(github.event) }}'); do
            MESSAGE=$(jq -r ".commits[] | select(.id==\"$COMMIT\") | .message" <<< '${{ toJson(github.event) }}')
            URL=$(jq -r ".commits[] | select(.id==\"$COMMIT\") | .url" <<< '${{ toJson(github.event) }}')
            AUTHOR=$(jq -r ".commits[] | select(.id==\"$COMMIT\") | .author.name" <<< '${{ toJson(github.event) }}')
            SHORT_COMMIT=${COMMIT:0:7}
            COMMIT_LIST="$COMMIT_LIST\n[$SHORT_COMMIT]($URL): $MESSAGE – $AUTHOR"
          done

          PAYLOAD=$(jq -n \
            --arg content "👤 *${{ github.actor }}* pushed to **${{ github.ref_name }}** in **${{ github.repository }}**\n🔗 [Compare changes](${{ github.event.compare }})\n$COMMIT_LIST" \
            '{content: $content}')

          curl -H "Content-Type: application/json" \
               -d "$PAYLOAD" \
               ${{ secrets.DISCORD_WEBHOOK }}

